apiVersion: v1
kind: Pod
metadata:
  namespace: acm-ns-pod
  name: busybox-test
  labels:
    app: busybox-test
spec:
  containers:
  - name: myapp-container
    image: docker.io/busybox:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    #securityContext:
    #    capabilities:
    #      add:
    #        - NET_RAW
